// The food catalogue: Livsmedelsverket's database plus whatever the user has added.
//
// The bundled database is optional. It is generated by scripts/build-foods.mjs and may not
// be there — an instance that never ran the script still works, on the user's own foods.
// Everything here therefore treats an empty catalogue as ordinary, not as an error state.

import { FOODS, FOODS_SOURCE } from './foods-data.js'

export { FOODS_SOURCE }

/** Nutrients carried per 100 g. Kept short on purpose: these are the ones a label shows. */
export const NUTRIENTS = ['kcal', 'carb', 'sugar', 'prot', 'fat', 'sat', 'fib', 'salt']

// English source strings, so they double as i18n keys.
export const NUTRIENT_NAME = {
  kcal: 'Calories', carb: 'Carbs', sugar: 'of which sugars', prot: 'Protein',
  fat: 'Fat', sat: 'of which saturated', fib: 'Fibre', salt: 'Salt'
}
export const NUTRIENT_UNIT = { kcal: 'kcal', carb: 'g', sugar: 'g', prot: 'g', fat: 'g', sat: 'g', fib: 'g', salt: 'g' }

/** Is the bundled database present? The UI says so plainly when it is not. */
export const hasFoodDb = () => FOODS.length > 0

const IDX = {}
FOODS.forEach(f => { IDX[f.id] = f })

/** Every food available to this profile — the user's own first, so they win a name clash. */
export const allFoods = st => [...(st && st.myFoods ? st.myFoods : []), ...FOODS]

/** Look one up by id, across both sources. */
export function foodOf(st, id) {
  const own = (st && st.myFoods ? st.myFoods : []).find(f => f.id === id)
  return own || IDX[id] || null
}

/** An id → food map, for turning a meal's items into numbers without repeated scans. */
export function foodMap(st) {
  const m = Object.create(null)
  for (const f of FOODS) m[f.id] = f
  for (const f of (st && st.myFoods ? st.myFoods : [])) m[f.id] = f
  return m
}

// Swedish food names are full of å, ä and ö, and nobody types them into a search box on a
// phone mid-breakfast. Folding them means "kottbullar" finds "köttbullar".
const fold = s => String(s || '').toLowerCase()
  .replace(/[åä]/g, 'a').replace(/ö/g, 'o').replace(/é/g, 'e')

/**
 * Search by name. A word that starts a word in the name ranks above one found mid-word, so
 * "mjölk" puts plain milk above "mjölkchoklad" — the thing you meant is the thing you get.
 */
export function searchFoods(st, q, limit = 40) {
  const needle = fold(q).trim()
  if (!needle) return []
  const terms = needle.split(/\s+/).filter(Boolean)
  const out = []
  for (const f of allFoods(st)) {
    const hay = fold(f.n)
    if (!terms.every(t => hay.includes(t))) continue
    // Rank: exact name, then starts-with, then word-boundary, then anywhere. Own foods get
    // a nudge so a saved "min yoghurt" beats forty catalogue yoghurts.
    const first = terms[0]
    let score = hay === needle ? 0 : hay.startsWith(first) ? 1 : new RegExp('\\b' + first.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).test(hay) ? 2 : 3
    if (f.own) score -= 0.5
    out.push({ f, score, len: hay.length })
  }
  // Shorter names first within a rank: a short name is the plain version of the thing.
  out.sort((a, b) => a.score - b.score || a.len - b.len)
  return out.slice(0, limit).map(x => x.f)
}
