// Generated by scripts/build-foods.mjs from Livsmedelsverkets livsmedelsdatabas (CC BY 4.0).
// Not committed with data: the database is fetched and written here by the script, the same
// way the exercise media is fetched rather than shipped. An empty catalogue is a supported
// state — the app runs on your own foods until you build this.
//
//   node scripts/build-foods.mjs
//
// Values are per 100 g. `carb` is Livsmedelsverket's own "Kolhydrater" field, carried
// through unchanged rather than reinterpreted — see the script for what that means.
export const FOODS = []
export const FOODS_SOURCE = null   // { name, version, built } once generated
